# Generated by Django 5.2.3 on 2025-06-23 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodoaquisicao',
            options={'verbose_name': 'Método de Aquisição', 'verbose_name_plural': 'Método de Aquisição'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='configuracao',
            field=models.CharField(blank=True, choices=[('VIVO', 'Vivo'), ('CLARO', 'Claro'), ('TIM', 'Tim'), ('OI', 'Oi'), ('ARQIA', 'Arquia'), ('OUTRO', 'Outro')], default='VIVO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='metodo_aquisicao',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.metodoaquisicao'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20, verbose_name='Status do Dispositivo'),
        ),
        migrations.AlterField(
            model_name='posto',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posto',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='posto',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posto',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='posto',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
