# Generated by Django 5.2.3 on 2025-06-23 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoAquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebs.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serial', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('configuracao', models.TextField(blank=True)),
                ('imei', models.CharField(blank=True, max_length=15)),
                ('numero', models.CharField(blank=True, max_length=15)),
                ('dados', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('leitura', models.BooleanField(default=False)),
                ('ligacao', models.BooleanField(default=False)),
                ('base', models.BooleanField(default=False)),
                ('bateria', models.BooleanField(default=False)),
                ('fonte', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebs.cliente')),
                ('metodo_aquisicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.metodoaquisicao')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebs.posto')),
            ],
        ),
    ]
