# Generated by Django 5.2.3 on 2025-06-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0003_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='data_entrada',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de Entrada'),
        ),
    ]
