# Generated by Django 5.2.3 on 2025-06-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0004_dispositivo_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
