# Generated by Django 5.2.3 on 2025-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0005_alter_dispositivo_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posto',
            name='status',
            field=models.CharField(default='Ativo', max_length=20),
        ),
    ]
