# Generated by Django 5.2.3 on 2025-06-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0008_comentarioticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='usuario_solicitante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do solicitante'),
        ),
    ]
